from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from textwrap import indent
from uuid import uuid4

import yaml

from .workspace import HarnessError, Workspace


PRESET_ID = re.compile(r"[a-z0-9][a-z0-9-]*\Z")
PRESET_MARKER = ".asl-preset-projection.json"
TOP_LEVEL_ROW = re.compile(r"(?ms)^- id: (?P<id>[^\r\n]+)\r?\n.*?(?=^- id: |\Z)")
GENERATED_DIRECTORIES = {
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".svn",
    "__pycache__",
    "node_modules",
}
GENERATED_FILES = {".DS_Store", "Thumbs.db"}


def _ignore_generated(_directory: str, names: list[str]) -> set[str]:
    ignored = {
        name
        for name in names
        if name in GENERATED_DIRECTORIES
        or name in GENERATED_FILES
        or name.endswith((".pyc", ".pyo"))
        or name == ".env"
        or (name.startswith(".env.") and name != ".env.example")
    }
    return ignored


def _replace_top_level_row(text: str, row_id: str, replacement: str) -> str:
    matches = [match for match in TOP_LEVEL_ROW.finditer(text) if match.group("id").strip() == row_id]
    if len(matches) != 1:
        raise HarnessError(
            "DEEPSEEK_BASE_INVALID",
            f"base preset must contain exactly one top-level {row_id!r} row",
        )
    match = matches[0]
    return text[: match.start()] + replacement.rstrip() + "\n" + text[match.end() :]


def _clean_generated_composition(text: str) -> str:
    lines = [line for line in text.splitlines() if not line.startswith("#")]
    cleaned = re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()
    return "# Generated by ASL Harness from a known-good base preset. Edit the Environment and re-export instead of editing this projection.\n\n" + cleaned + "\n"


def _mode_persona(workspace: Workspace, mode_id: str) -> str:
    mode = workspace.modes[mode_id]
    text = f"""You are an agent running ASL Mode {mode_id}.

Environment truth: {workspace.root}

Compact Profile:
{workspace.profile.strip()}

Mode boundary:
{mode.document.strip()}

Use this as a broad working environment, not a Workflow. Select complete local Skills dynamically from the user's Goal. Read every selected Skill package fully and satisfy its completion standards even inside a larger task. External Prompt, MCP, Agent, API, model, command, script, or remote Skill may be used only through a formal projected local Skill. A user-directed source may be integrated directly after full review; Candidate and Trial are only for concrete uncertainty. Keep one-off evidence and Artifacts in the current Case. Record durable feedback only when the user states it explicitly.

Do not infer durable Environment changes from ordinary work. For an explicit user request, use the Harness system maintenance path from the current Mode, change the smallest fitting truth, run deterministic validation, and leave a reviewable Git diff. Mode selection never authorizes deletion, publication, payment, login, private-data access, messages, or external writes; those actions remain behind the current Host's native authorization boundary.

The current DeepSeek Harness agent is the only executor. ASL does not add a second scheduler or Agent loop.
"""
    return text.replace("{{", "{ {").replace("}}", "} }")


def _persona_row(persona: str) -> str:
    rendered = yaml.safe_dump(
        persona.strip(), allow_unicode=True, default_style="|", sort_keys=False
    ).rstrip()
    return "- id: persona\n  name: '@deepseek-ai/dsh-persona'\n  config:\n    text: " + indent(
        rendered, "    "
    ).lstrip()


def _skill_filesystem_row(final_skill_root: Path) -> str:
    rendered_path = json.dumps(str(final_skill_root), ensure_ascii=False)
    return f"""- id: skill-filesystem
  name: '@deepseek-ai/dsh-skill-filesystem'
  config:
    includeDefaultRoots: false
    customSkillDirs:
      - {rendered_path}
"""


def _read_marker(path: Path) -> dict | None:
    try:
        value = json.loads((path / PRESET_MARKER).read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _description(document: str, mode_id: str) -> str:
    for line in document.splitlines():
        value = line.strip()
        if value and not value.startswith("#"):
            return value
    return f"ASL Mode {mode_id} 的本地能力环境。"


def verify_preset(
    workspace: Workspace,
    mode_id: str,
    output: str | Path,
) -> list[str]:
    if mode_id not in workspace.modes:
        raise HarnessError("MODE_NOT_ACTIVE", f"Mode is not active: {mode_id}")
    target = Path(output).resolve()
    marker = _read_marker(target)
    expected_keys = {
        "version",
        "hostId",
        "environment",
        "environmentCommit",
        "sourceFingerprint",
        "mode",
        "basePreset",
        "skills",
    }
    skill_ids = workspace.mode_skill_ids(mode_id)
    if (
        marker is None
        or set(marker) != expected_keys
        or marker.get("version") != 1
        or marker.get("hostId") != "deepseek-harness"
        or marker.get("environment") != str(workspace.root)
        or marker.get("mode") != mode_id
        or marker.get("skills") != list(skill_ids)
        or not isinstance(marker.get("basePreset"), str)
    ):
        raise HarnessError(
            "DEEPSEEK_PRESET_INVALID", "DeepSeek preset marker is invalid"
        )
    composition_path = target / "agent.cordis.yml"
    preset_path = target / "preset.yml"
    try:
        composition = composition_path.read_text(encoding="utf-8")
        preset_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as error:
        raise HarnessError(
            "DEEPSEEK_PRESET_INVALID", "DeepSeek preset metadata is incomplete"
        ) from error
    expected_skill_root = json.dumps(str(target / "skills"), ensure_ascii=False)
    if expected_skill_root not in composition:
        raise HarnessError(
            "DEEPSEEK_PRESET_INVALID", "DeepSeek preset Skill root is invalid"
        )
    for skill_id in skill_ids:
        if not (target / "skills" / skill_id / "SKILL.md").is_file():
            raise HarnessError(
                "DEEPSEEK_PRESET_INVALID",
                f"DeepSeek preset Skill is incomplete: {skill_id}",
            )
    warnings = []
    if marker["sourceFingerprint"] != workspace.source_fingerprint(mode_id):
        warnings.append(
            "Environment content changed after preset export; run deepseek.preset.export again."
        )
    if marker["environmentCommit"] != workspace.git_commit:
        warnings.append(
            "Environment Git HEAD changed after preset export; run deepseek.preset.export again."
        )
    return warnings


def export_preset(
    workspace: Workspace,
    mode_id: str,
    base_preset: str | Path,
    output: str | Path,
) -> dict:
    if mode_id not in workspace.modes:
        raise HarnessError("MODE_NOT_ACTIVE", f"Mode is not active: {mode_id}")
    base = Path(base_preset).resolve()
    target = Path(output).resolve()
    if not PRESET_ID.fullmatch(target.name):
        raise HarnessError(
            "DEEPSEEK_PRESET_ID_INVALID",
            "DeepSeek preset output directory name must match [a-z0-9][a-z0-9-]*",
        )
    if not base.is_dir() or not (base / "agent.cordis.yml").is_file():
        raise HarnessError(
            "DEEPSEEK_BASE_INVALID", "base preset must contain agent.cordis.yml"
        )
    if target == base or target.is_relative_to(base) or base.is_relative_to(target):
        raise HarnessError(
            "DEEPSEEK_OUTPUT_INVALID", "base preset and output must be separate directories"
        )
    old_marker = _read_marker(target) if target.exists() else None
    if target.exists() and (
        old_marker is None
        or old_marker.get("environment") != str(workspace.root)
        or old_marker.get("mode") != mode_id
    ):
        raise HarnessError(
            "DEEPSEEK_PRESET_COLLISION",
            f"refusing to overwrite a preset not managed by this Mode: {target}",
        )

    temporary = target.with_name(f".{target.name}.asl-tmp-{uuid4().hex}")
    backup = target.with_name(f".{target.name}.asl-backup-{uuid4().hex}")
    try:
        shutil.copytree(base, temporary, symlinks=False, ignore=_ignore_generated)
        skill_root = temporary / "skills"
        if skill_root.exists():
            shutil.rmtree(skill_root)
        skill_root.mkdir(parents=True)
        for skill_id in workspace.mode_skill_ids(mode_id):
            shutil.copytree(
                workspace.skills[skill_id].path,
                skill_root / skill_id,
                symlinks=False,
                ignore=_ignore_generated,
            )

        composition_path = temporary / "agent.cordis.yml"
        composition = _clean_generated_composition(
            composition_path.read_text(encoding="utf-8")
        )
        composition = _replace_top_level_row(
            composition, "persona", _persona_row(_mode_persona(workspace, mode_id))
        )
        composition = _replace_top_level_row(
            composition,
            "skill-filesystem",
            _skill_filesystem_row(target / "skills"),
        )
        composition_path.write_text(composition, encoding="utf-8", newline="\n")

        metadata = {
            "name": f"ASL · {mode_id}",
            "description": _description(workspace.modes[mode_id].document, mode_id),
        }
        (temporary / "preset.yml").write_text(
            yaml.safe_dump(metadata, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
            newline="\n",
        )
        marker = {
            "version": 1,
            "hostId": "deepseek-harness",
            "environment": str(workspace.root),
            "environmentCommit": workspace.git_commit,
            "sourceFingerprint": workspace.source_fingerprint(mode_id),
            "mode": mode_id,
            "basePreset": str(base),
            "skills": list(workspace.mode_skill_ids(mode_id)),
        }
        (temporary / PRESET_MARKER).write_text(
            json.dumps(marker, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
            + "\n",
            encoding="utf-8",
        )

        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            target.rename(backup)
        try:
            temporary.rename(target)
        except Exception:
            if backup.exists() and not target.exists():
                backup.rename(target)
            raise
        if backup.exists():
            shutil.rmtree(backup)
        return marker | {"output": str(target)}
    finally:
        if temporary.exists():
            shutil.rmtree(temporary)
        if backup.exists() and target.exists():
            shutil.rmtree(backup)
